<?php
/*
 * @file
 * central site module for patterns.
 *
 * the module'name is centralSite.
 * there are three parts:
 * 		1,hook_help.
 * 		2,hook_menu.
 * 			two path: one is on the Navigation.the other is a configure page.
 */

module_load_include('inc', 'centralSite', 'theme/theme');

/**
 * Implements hook_help().
 */
function centralSite_help($path,$arg) {
  switch ($path) {
    case "admin/help#centralSite":
      return '<p>'.t("help for centralSite module").'<p>';
      break;
  }
}

/**
 * Implements hook_permission().
 */
function centralSite_permission() {
  return array(
    'access centralSite' => array(
      'title' => t('Access permission for the centralSite module'),
      )
    );
}

/**
 * Implements hook_menu().
 *
 * the path'callback function is _centralSite_page().
 * second: configure form page.
 */
function centralSite_menu() {
  $items = array();  
  $items['centralSite'] = array(
    'title' => 'centralSite',
    'page callback' => '_centralSite_page',
    'access arguments' => array('access centralSite'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * a function used in the form.
 *
 * Use Database API to retrieve the patterns from patterns table.
 */
function centralSite_get_pattern_from_db() {
  $result = db_select('patterns', 'p')
                  ->fields('p', array())
                  ->orderBy('pid', 'DESC')
                  ->range(0,10)
                  ->execute()
                  ->fetchAll();

  $patterns = array();

  foreach ($result as $pattern) {
    $patterns[$pattern->pid] = $pattern;
    $data = unserialize($pattern->pattern);
    $patterns[$pattern->pid]->pattern = $data;
    $patterns[$pattern->pid]->info = $data['info'];
  }

  return $patterns;
}

/**
 * hook_menu callback function.
 */
function _centralSite_page() {
  drupal_add_css(drupal_get_path('module', 'centralSite') . '/centralSite.css');
  $result = centralSite_get_pattern_from_db();
  $page_array = theme('centralSite_pattern_list',array(
                    'patterns' => $result,
  ));
  return $page_array; 
}
